name: rust-svelte-fullstack
version: "3"

services:
  db:
    image: "postgres:latest"
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./migration/000_init.sql:/docker-entrypoint-initdb.d/000_init.sql
networks:
  postgres-network:
    driver: bridge
volumes:
  db:
    driver: local
