FROM node:20 as builder
RUN npm install -g pnpm

WORKDIR /app

COPY ./ ./
WORKDIR /app/frontend

# COPY ./frontend/package.json ./frontend
# COPY ./frontend/pnpm-lock.yaml ./frontend
# WORKDIR /app/frontend

RUN pnpm install
RUN pnpm run build
# CMD echo test

FROM rust:1.75

WORKDIR /app

COPY ./ ./
COPY --from=builder /app/frontend/static/ /app/static/

# CMD echo test
EXPOSE 8000:8000

# RUN cargo install
RUN cargo build

CMD ["cargo", "run"]
