name: rust-svelte-fullstack
version: "3"

services:
  server:
    # build:
    #   context: .
    #   target: final
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - postgres-network
  db:
    image: "postgres:latest"
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

      #migration:
networks:
  postgres-network:
    driver: bridge
volumes:
  db:
    driver: local
